import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/NavBar";
import { afacad } from "./components/fonts";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Rae's Creations",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${afacad.className} antialiased`}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
